language: java
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings travis/settings.xml || mvn clean verify --settings travis/settings.xml"
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - develop-ga
jdk:
  - oraclejdk8
env:
  global:
    - secure: "aztndlDw36TZu2XhszCZjg+URl1wVVLd3BaHD5f5r0oXPExqnc7exlJUYoA6xKv4k2rG5BM0MunewMhzznzDoYj7ilTR0aAIkgSUMVWWxLY/peFwtcPSpbQlPT3mCVFqhnaYtKribHDUz6I2SSMnHNxjV82GI3txxeHeURoOQVg="
    - secure: "KK+m1Ck/Bo7xsLYY+2Qi5pI4vIw9Up6mqz6tXAbRKLP/jzzOJSHCMlHQo26g7M3x6YRIubYdoiEtYw4dX5dcy8rsAYbrhf89CHpNMS4a11TqbYQz/yBsH+1oWR6nvUo+dVvtcaOQa4oIOJMuqmDP6LsCrk89ecWC0UD0l0BcA+k="
notifications:
        slack:
                secure: "IpJwQWNNYznx31jnLGM+Yc+yAowdo1R2DulRl2L4ZFM6ucO9PNG2rbk5DK9lVcur2TSB096dB1ygWCYGv8WSRkHX2t8agKApD39XK65ELjzTusLDz0tWAKx5k4md8dEE9Kv6nfmVA9ZgVdf7ZuR0bKK/leAwzmKsVTirJlmdrIw="


